In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from googletrans import Translator

In [3]:
df_test = ("../files/test.csv")
df_train = ("../files/sales_train_v2.csv")

df_test = pd.read_csv(df_test, sep = ",") #(214200, 3)
df_train = pd.read_csv(df_train, sep = ",") # (2935849, 6)

In [4]:
df_items = ("../files/items.csv")
df_item_categories = ("../files/item_categories.csv")
df_shops = ("../files/shops.csv")

df_items = pd.read_csv(df_items, sep = ",") #(214200, 3)
df_item_categories = pd.read_csv(df_item_categories, sep = ",") # (2935849, 6) 
df_shops = pd.read_csv(df_shops, sep = ",") #(214200, 3)

In [5]:
translator = Translator()
item_category_name_ko = pd.Series([str(translator.translate(category_name, dest = "ko").text) for category_name in df_item_categories.item_category_name])
df_item_categories.item_category_name = item_category_name_ko
df_item_categories.item_category_name


shop_name_ko = pd.Series([str(translator.translate(shop_nm, dest = "ko").text) for shop_nm in df_shops.shop_name])
df_shops.shop_name = shop_name_ko

In [6]:
df_shops

                                          shop_name  shop_id
0                      Yakutsk Ordzhonikidze, 56 프랑        0
1                                   야쿠 츠크 TC "중앙"프랑        1
2                                아디 게아 쇼핑 센터 "Mega"        2
3                            발라 시카 TRK "10 월 키노 미르"        3
4          볼츠키 (Volzhsky) 쇼핑 센터 "볼가 몰 (Volga Mall)"        4
5                     볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"        5
6                        보로 네즈 (Porkhanovskaya, 13)        6
7                              Voronezh TRC "막시 미르"        7
8                          Voronezh TRC 도시 공원 "졸업생"        8
9                                             외환 거래        9
10                        Zhukovsky Str. 차 칼로프 39m?       10
11                     Zhukovsky Str. Chkalov 39 m²       11
12                                     온라인 상점 비상 사태       12
13                                  카잔 TC "Bahetle"       13
14                                 카잔 TC "파크 하우스"II       14
15                                 칼루가 TRC "XXI 세기"       15
16                                        콜로세움 "리오"       16
17  크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 "Vzletka Plaza"       17
18           크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 "June"       18
19                             쿠르스크 TC "Pushkinsky"       19
20                                        모스크바 "판매"       20
21                            모스크바 MTRTS "Afi Mall"       21
22                                     모스크바 쇼핑몰 С21       22
23                    모스크바 TC "Budenovskiy"(pav.A2)       23
24                    모스크바 TC "Budenovskiy"(pav.K7)       24
25                                  모스크바 TRK "아트리움"       25
26                     모스크바 무역 센터 "Areal"(Belyaevo)       26
27                          모스크바 ТЦ "메가 벨라 야 다차 II"       27
28                         모스크바 ТЦ "메가 Teply 스탠"II에       28
29                        모스크바 TC "신세기"(Novokosino)       29
30                          모스크바 TP TPP "Perlovski"       30
31                            모스크바 ТЦ "Семеновский"       31
32                              모스크바 쇼핑 센터 "실버 하우스"       32
33                              Mytischi TRK "XL-3"       33
34                             N.Novgorod TRC "RIO"       34
35                       니즈니 노브 고로드 쇼핑몰 "Fantastic"       35
36                     노보시비르스크 TRC "갤러리 노보 시비 르 스크"       36
37                                  노보시비르스크 TC "메가"       37
38                                     옴 스크 TC "메가"       38
39             RostovNaDon TRK "Megacenter Horizon"       39
40      RostovNaDonu TRC "Megacenter Horizon"Island       40
41                             RostovNaDonu TC "메가"       41
42                                 SPb TC "넵 스키 센터"       42
43                                    SPb TK "센나 야"       43
44                                     사마라 TP "멜로디"       44
45                                  사마라 TC "파크 하우스"       45
46                             세르 기 예프 포사드 TC "7YA"       46
47                Surgut 쇼핑 및 엔터테인먼트 센터 "City Mall"       47
48                               톰 스크 SEC "에메랄드 시티"       48
49                                Tyumen SEC "크리스탈"       49
50                                    튜멘 쇼핑 센터 "굿윈"       50
51                                 튜멘 쇼핑 센터 "그린 비치"       51
52                                       우파 TC "중부"       52
53                                      우파 TC "가족"2       53
54                                   Khimki ТЦ "메가"       54
55                                 디지털 창고 1C-Online       55
56                                   체 호프 SEC "카니발"       56
57                        Yakutsk Ordzhonikidze, 56       57
58                                  야쿠 츠크 센트럴 쇼핑 센터       58
59                           야로 슬라 블 쇼핑 센터 "Altair"       59

In [7]:
df_shops['location'] = None
df_shops

                                          shop_name  shop_id location
0                      Yakutsk Ordzhonikidze, 56 프랑        0     None
1                                   야쿠 츠크 TC "중앙"프랑        1     None
2                                아디 게아 쇼핑 센터 "Mega"        2     None
3                            발라 시카 TRK "10 월 키노 미르"        3     None
4          볼츠키 (Volzhsky) 쇼핑 센터 "볼가 몰 (Volga Mall)"        4     None
5                     볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"        5     None
6                        보로 네즈 (Porkhanovskaya, 13)        6     None
7                              Voronezh TRC "막시 미르"        7     None
8                          Voronezh TRC 도시 공원 "졸업생"        8     None
9                                             외환 거래        9     None
10                        Zhukovsky Str. 차 칼로프 39m?       10     None
11                     Zhukovsky Str. Chkalov 39 m²       11     None
12                                     온라인 상점 비상 사태       12     None
13                                  카잔 TC "Bahetle"       13     None
14                                 카잔 TC "파크 하우스"II       14     None
15                                 칼루가 TRC "XXI 세기"       15     None
16                                        콜로세움 "리오"       16     None
17  크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 "Vzletka Plaza"       17     None
18           크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 "June"       18     None
19                             쿠르스크 TC "Pushkinsky"       19     None
20                                        모스크바 "판매"       20     None
21                            모스크바 MTRTS "Afi Mall"       21     None
22                                     모스크바 쇼핑몰 С21       22     None
23                    모스크바 TC "Budenovskiy"(pav.A2)       23     None
24                    모스크바 TC "Budenovskiy"(pav.K7)       24     None
25                                  모스크바 TRK "아트리움"       25     None
26                     모스크바 무역 센터 "Areal"(Belyaevo)       26     None
27                          모스크바 ТЦ "메가 벨라 야 다차 II"       27     None
28                         모스크바 ТЦ "메가 Teply 스탠"II에       28     None
29                        모스크바 TC "신세기"(Novokosino)       29     None
30                          모스크바 TP TPP "Perlovski"       30     None
31                            모스크바 ТЦ "Семеновский"       31     None
32                              모스크바 쇼핑 센터 "실버 하우스"       32     None
33                              Mytischi TRK "XL-3"       33     None
34                             N.Novgorod TRC "RIO"       34     None
35                       니즈니 노브 고로드 쇼핑몰 "Fantastic"       35     None
36                     노보시비르스크 TRC "갤러리 노보 시비 르 스크"       36     None
37                                  노보시비르스크 TC "메가"       37     None
38                                     옴 스크 TC "메가"       38     None
39             RostovNaDon TRK "Megacenter Horizon"       39     None
40      RostovNaDonu TRC "Megacenter Horizon"Island       40     None
41                             RostovNaDonu TC "메가"       41     None
42                                 SPb TC "넵 스키 센터"       42     None
43                                    SPb TK "센나 야"       43     None
44                                     사마라 TP "멜로디"       44     None
45                                  사마라 TC "파크 하우스"       45     None
46                             세르 기 예프 포사드 TC "7YA"       46     None
47                Surgut 쇼핑 및 엔터테인먼트 센터 "City Mall"       47     None
48                               톰 스크 SEC "에메랄드 시티"       48     None
49                                Tyumen SEC "크리스탈"       49     None
50                                    튜멘 쇼핑 센터 "굿윈"       50     None
51                                 튜멘 쇼핑 센터 "그린 비치"       51     None
52                                       우파 TC "중부"       52     None
53                                      우파 TC "가족"2       53     None
54                                   Khimki ТЦ "메가"       54     None
55                                 디지털 창고 1C-Online       55     None
56                                   체 호프 SEC "카니발"       56     None
57                        Yakutsk Ordzhonikidze, 56       57     None
58                                  야쿠 츠크 센트럴 쇼핑 센터       58     None
59                           야로 슬라 블 쇼핑 센터 "Altair"       59     None

In [8]:
df_shops.loc[0:1,'location'] = '야쿠츠크'
df_shops.loc[20:33,'location'] = '모스크바'
df_shops.loc[2,'location'] = '아디게아'
df_shops.loc[3,'location'] ='발라시카' 
df_shops.loc[4,'location'] = '볼츠키'
df_shops.loc[5,'location'] = '볼로그다'
df_shops.loc[6:8,'location'] = '보로네시'
df_shops.loc[9,'location'] = '기타'
df_shops.loc[10:11,'location'] = '기타'
df_shops.loc[12,'location'] = '기타'
df_shops.loc[13:14,'location'] = '카잔'
df_shops.loc[15,'location'] = '칼루가'
df_shops.loc[16,'location'] = '기타'
df_shops.loc[17:18,'location'] = '크라스노야르스크'
df_shops.loc[34:35,'location'] = '노브고로드'
df_shops.loc[19,'location'] = '쿠르스크'
df_shops.loc[36:37,'location'] ='노보시비르스크'
df_shops.loc[38,'location']='옴스크'
df_shops.loc[39:41,'location']='로스토프나도누'
df_shops.loc[42:43,'location']='상트페테르부르크'
df_shops.loc[44:45,'location']='사마라'
df_shops.loc[46,'location']='세르기예프 포사트'
df_shops.loc[47,'location']='수르구트'
df_shops.loc[48,'location']='톰스크'
df_shops.loc[49:51,'location']='튜멘'
df_shops.loc[52:53,'location']='우파'
df_shops.loc[54,'location']='힘키'
df_shops.loc[55:56,'location']='기타'
df_shops.loc[57:58,'location']= '야쿠츠크'
df_shops.loc[59,'location']='야로슬라블'
df_shops

                                          shop_name  shop_id   location
0                      Yakutsk Ordzhonikidze, 56 프랑        0       야쿠츠크
1                                   야쿠 츠크 TC "중앙"프랑        1       야쿠츠크
2                                아디 게아 쇼핑 센터 "Mega"        2       아디게아
3                            발라 시카 TRK "10 월 키노 미르"        3       발라시카
4          볼츠키 (Volzhsky) 쇼핑 센터 "볼가 몰 (Volga Mall)"        4        볼츠키
5                     볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"        5       볼로그다
6                        보로 네즈 (Porkhanovskaya, 13)        6       보로네시
7                              Voronezh TRC "막시 미르"        7       보로네시
8                          Voronezh TRC 도시 공원 "졸업생"        8       보로네시
9                                             외환 거래        9         기타
10                        Zhukovsky Str. 차 칼로프 39m?       10         기타
11                     Zhukovsky Str. Chkalov 39 m²       11         기타
12                                     온라인 상점 비상 사태       12         기타
13                                  카잔 TC "Bahetle"       13         카잔
14                                 카잔 TC "파크 하우스"II       14         카잔
15                                 칼루가 TRC "XXI 세기"       15        칼루가
16                                        콜로세움 "리오"       16         기타
17  크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 "Vzletka Plaza"       17   크라스노야르스크
18           크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 "June"       18   크라스노야르스크
19                             쿠르스크 TC "Pushkinsky"       19       쿠르스크
20                                        모스크바 "판매"       20       모스크바
21                            모스크바 MTRTS "Afi Mall"       21       모스크바
22                                     모스크바 쇼핑몰 С21       22       모스크바
23                    모스크바 TC "Budenovskiy"(pav.A2)       23       모스크바
24                    모스크바 TC "Budenovskiy"(pav.K7)       24       모스크바
25                                  모스크바 TRK "아트리움"       25       모스크바
26                     모스크바 무역 센터 "Areal"(Belyaevo)       26       모스크바
27                          모스크바 ТЦ "메가 벨라 야 다차 II"       27       모스크바
28                         모스크바 ТЦ "메가 Teply 스탠"II에       28       모스크바
29                        모스크바 TC "신세기"(Novokosino)       29       모스크바
30                          모스크바 TP TPP "Perlovski"       30       모스크바
31                            모스크바 ТЦ "Семеновский"       31       모스크바
32                              모스크바 쇼핑 센터 "실버 하우스"       32       모스크바
33                              Mytischi TRK "XL-3"       33       모스크바
34                             N.Novgorod TRC "RIO"       34      노브고로드
35                       니즈니 노브 고로드 쇼핑몰 "Fantastic"       35      노브고로드
36                     노보시비르스크 TRC "갤러리 노보 시비 르 스크"       36    노보시비르스크
37                                  노보시비르스크 TC "메가"       37    노보시비르스크
38                                     옴 스크 TC "메가"       38        옴스크
39             RostovNaDon TRK "Megacenter Horizon"       39    로스토프나도누
40      RostovNaDonu TRC "Megacenter Horizon"Island       40    로스토프나도누
41                             RostovNaDonu TC "메가"       41    로스토프나도누
42                                 SPb TC "넵 스키 센터"       42   상트페테르부르크
43                                    SPb TK "센나 야"       43   상트페테르부르크
44                                     사마라 TP "멜로디"       44        사마라
45                                  사마라 TC "파크 하우스"       45        사마라
46                             세르 기 예프 포사드 TC "7YA"       46  세르기예프 포사트
47                Surgut 쇼핑 및 엔터테인먼트 센터 "City Mall"       47       수르구트
48                               톰 스크 SEC "에메랄드 시티"       48        톰스크
49                                Tyumen SEC "크리스탈"       49         튜멘
50                                    튜멘 쇼핑 센터 "굿윈"       50         튜멘
51                                 튜멘 쇼핑 센터 "그린 비치"       51         튜멘
52                                       우파 TC "중부"       52         우파
53                                      우파 TC "가족"2       53         우파
54                                   Khimki ТЦ "메가"       54         힘키
55                                 디지털 창고 1C-Online       55         기타
56                                   체 호프 SEC "카니발"       56         기타
57                        Yakutsk Ordzhonikidze, 56       57       야쿠츠크
58                                  야쿠 츠크 센트럴 쇼핑 센터       58       야쿠츠크
59                           야로 슬라 블 쇼핑 센터 "Altair"       59      야로슬라블

In [9]:
df_shops['direction'] = None
df_shops

,shop_name,shop_id,location,direction
0,"Yakutsk Ordzhonikidze, 56 프랑",0,야쿠츠크,None
1,"야쿠 츠크 TC ""중앙""프랑",1,야쿠츠크,None
2,"아디 게아 쇼핑 센터 ""Mega""",2,아디게아,None
3,"발라 시카 TRK ""10 월 키노 미르""",3,발라시카,None
4,"볼츠키 (Volzhsky) 쇼핑 센터 ""볼가 몰 (Volga Mall)""",4,볼츠키,None
5,"볼 로그 다 쇼핑 및 엔터테인먼트 센터 ""마멀레이드""",5,볼로그다,None
6,"보로 네즈 (Porkhanovskaya, 13)",6,보로네시,None
7,"Voronezh TRC ""막시 미르""",7,보로네시,None
8,"Voronezh TRC 도시 공원 ""졸업생""",8,보로네시,None
9,외환 거래,9,기타,None
10,Zhukovsky Str. 차 칼로프 39m?,10,기타,None
11,Zhukovsky Str. Chkalov 39 m²,11,기타,None
12,온라인 상점 비상 사태,12,기타,None
13,"카잔 TC ""Bahetle""",13,카잔,None
14,"카잔 TC ""파크 하우스""II",14,카잔,None
15,"칼루가 TRC ""XXI 세기""",15,칼루가,None
16,"콜로세움 ""리오""",16,기타,None
17,"크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 ""Vzletka Plaza""",17,크라스노야르스크,None
18,"크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 ""June""",18,크라스노야르스크,None
19,"쿠르스크 TC ""Pushkinsky""",19,쿠르스크,None
20,"모스크바 ""판매""",20,모스크바,None
21,"모스크바 MTRTS ""Afi Mall""",21,모스크바,None
22,모스크바 쇼핑몰 С21,22,모스크바,None
23,"모스크바 TC ""Budenovskiy""(pav.A2)",23,모스크바,None
24,"모스크바 TC ""Budenovskiy""(pav.K7)",24,모스크바,None
25,"모스크바 TRK ""아트리움""",25,모스크바,None
26,"모스크바 무역 센터 ""Areal""(Belyaevo)",26,모스크바,None
27,"모스크바 ТЦ ""메가 벨라 야 다차 II""",27,모스크바,None
28,"모스크바 ТЦ ""메가 Teply 스탠""II에",28,모스크바,None
29,"모스크바 TC ""신세기""(Novokosino)",29,모스크바,None
30,"모스크바 TP TPP ""Perlovski""",30,모스크바,None
31,"모스크바 ТЦ ""Семеновский""",31,모스크바,None
32,"모스크바 쇼핑 센터 ""실버 하우스""",32,모스크바,None
33,"Mytischi TRK ""XL-3""",33,모스크바,None
34,"N.Novgorod TRC ""RIO""",34,노브고로드,None
35,"니즈니 노브 고로드 쇼핑몰 ""Fantastic""",35,노브고로드,None
36,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",36,노보시비르스크,None
37,"노보시비르스크 TC ""메가""",37,노보시비르스크,None
38,"옴 스크 TC ""메가""",38,옴스크,None
39,"RostovNaDon TRK ""Megacenter Horizon""",39,로스토프나도누,None
40,"RostovNaDonu TRC ""Megacenter Horizon""Island",40,로스토프나도누,None
41,"RostovNaDonu TC ""메가""",41,로스토프나도누,None
42,"SPb TC ""넵 스키 센터""",42,상트페테르부르크,None
43,"SPb TK ""센나 야""",43,상트페테르부르크,None
44,"사마라 TP ""멜로디""",44,사마라,None
45,"사마라 TC ""파크 하우스""",45,사마라,None
46,"세르 기 예프 포사드 TC ""7YA""",46,세르기예프 포사트,None
47,"Surgut 쇼핑 및 엔터테인먼트 센터 ""City Mall""",47,수르구트,None
48,"톰 스크 SEC ""에메랄드 시티""",48,톰스크,None
49,"Tyumen SEC ""크리스탈""",49,튜멘,None
50,"튜멘 쇼핑 센터 ""굿윈""",50,튜멘,None
51,"튜멘 쇼핑 센터 ""그린 비치""",51,튜멘,None
52,"우파 TC ""중부""",52,우파,None
53,"우파 TC ""가족""2",53,우파,None
54,"Khimki ТЦ ""메가""",54,힘키,None
55,디지털 창고 1C-Online,55,기타,None
56,"체 호프 SEC ""카니발""",56,기타,None
57,"Yakutsk Ordzhonikidze, 56",57,야쿠츠크,None
58,야쿠 츠크 센트럴 쇼핑 센터,58,야쿠츠크,None
59,"야로 슬라 블 쇼핑 센터 ""Altair""",59,야로슬라블,None

In [10]:
df_shops.loc[0:1,'direction'] = '동부'
df_shops.loc[20:33,'direction'] = '서부'
df_shops.loc[2,'direction'] = '서부'
df_shops.loc[3,'direction'] ='서부' 
df_shops.loc[4,'direction'] = '서부'
df_shops.loc[5,'direction'] = '서부'
df_shops.loc[6:8,'direction'] = '서부'
df_shops.loc[9,'direction'] = '기타'
df_shops.loc[10:11,'direction'] = '기타'
df_shops.loc[12,'direction'] = '기타'
df_shops.loc[13:14,'direction'] = '서부'
df_shops.loc[15,'direction'] = '서부'
df_shops.loc[16,'direction'] = '기타'
df_shops.loc[17:18,'direction'] = '중부'
df_shops.loc[34:35,'direction'] = '서부'
df_shops.loc[19,'direction'] = '서부'
df_shops.loc[36:37,'direction'] ='중부'
df_shops.loc[38,'direction']='중부'
df_shops.loc[39:41,'direction']='서부'
df_shops.loc[42:43,'direction']='서부'
df_shops.loc[44:45,'direction']='서부'
df_shops.loc[46,'direction']='서부'
df_shops.loc[47,'direction']='중부'
df_shops.loc[48,'direction']='중부'
df_shops.loc[49:51,'direction']='중부'
df_shops.loc[52:53,'direction']='서부'
df_shops.loc[54,'direction']='서부'
df_shops.loc[55:56,'direction']='기타'
df_shops.loc[57:58,'direction']= '동부'
df_shops.loc[59,'direction']='서부'
df_shops

,shop_name,shop_id,location,direction
0,"Yakutsk Ordzhonikidze, 56 프랑",0,야쿠츠크,동부
1,"야쿠 츠크 TC ""중앙""프랑",1,야쿠츠크,동부
2,"아디 게아 쇼핑 센터 ""Mega""",2,아디게아,서부
3,"발라 시카 TRK ""10 월 키노 미르""",3,발라시카,서부
4,"볼츠키 (Volzhsky) 쇼핑 센터 ""볼가 몰 (Volga Mall)""",4,볼츠키,서부
5,"볼 로그 다 쇼핑 및 엔터테인먼트 센터 ""마멀레이드""",5,볼로그다,서부
6,"보로 네즈 (Porkhanovskaya, 13)",6,보로네시,서부
7,"Voronezh TRC ""막시 미르""",7,보로네시,서부
8,"Voronezh TRC 도시 공원 ""졸업생""",8,보로네시,서부
9,외환 거래,9,기타,기타
10,Zhukovsky Str. 차 칼로프 39m?,10,기타,기타
11,Zhukovsky Str. Chkalov 39 m²,11,기타,기타
12,온라인 상점 비상 사태,12,기타,기타
13,"카잔 TC ""Bahetle""",13,카잔,서부
14,"카잔 TC ""파크 하우스""II",14,카잔,서부
15,"칼루가 TRC ""XXI 세기""",15,칼루가,서부
16,"콜로세움 ""리오""",16,기타,기타
17,"크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 ""Vzletka Plaza""",17,크라스노야르스크,중부
18,"크라스 노야 르 스크 (Krasnoyarsk) 쇼핑 센터 ""June""",18,크라스노야르스크,중부
19,"쿠르스크 TC ""Pushkinsky""",19,쿠르스크,서부
20,"모스크바 ""판매""",20,모스크바,서부
21,"모스크바 MTRTS ""Afi Mall""",21,모스크바,서부
22,모스크바 쇼핑몰 С21,22,모스크바,서부
23,"모스크바 TC ""Budenovskiy""(pav.A2)",23,모스크바,서부
24,"모스크바 TC ""Budenovskiy""(pav.K7)",24,모스크바,서부
25,"모스크바 TRK ""아트리움""",25,모스크바,서부
26,"모스크바 무역 센터 ""Areal""(Belyaevo)",26,모스크바,서부
27,"모스크바 ТЦ ""메가 벨라 야 다차 II""",27,모스크바,서부
28,"모스크바 ТЦ ""메가 Teply 스탠""II에",28,모스크바,서부
29,"모스크바 TC ""신세기""(Novokosino)",29,모스크바,서부
30,"모스크바 TP TPP ""Perlovski""",30,모스크바,서부
31,"모스크바 ТЦ ""Семеновский""",31,모스크바,서부
32,"모스크바 쇼핑 센터 ""실버 하우스""",32,모스크바,서부
33,"Mytischi TRK ""XL-3""",33,모스크바,서부
34,"N.Novgorod TRC ""RIO""",34,노브고로드,서부
35,"니즈니 노브 고로드 쇼핑몰 ""Fantastic""",35,노브고로드,서부
36,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",36,노보시비르스크,중부
37,"노보시비르스크 TC ""메가""",37,노보시비르스크,중부
38,"옴 스크 TC ""메가""",38,옴스크,중부
39,"RostovNaDon TRK ""Megacenter Horizon""",39,로스토프나도누,서부
40,"RostovNaDonu TRC ""Megacenter Horizon""Island",40,로스토프나도누,서부
41,"RostovNaDonu TC ""메가""",41,로스토프나도누,서부
42,"SPb TC ""넵 스키 센터""",42,상트페테르부르크,서부
43,"SPb TK ""센나 야""",43,상트페테르부르크,서부
44,"사마라 TP ""멜로디""",44,사마라,서부
45,"사마라 TC ""파크 하우스""",45,사마라,서부
46,"세르 기 예프 포사드 TC ""7YA""",46,세르기예프 포사트,서부
47,"Surgut 쇼핑 및 엔터테인먼트 센터 ""City Mall""",47,수르구트,중부
48,"톰 스크 SEC ""에메랄드 시티""",48,톰스크,중부
49,"Tyumen SEC ""크리스탈""",49,튜멘,중부
50,"튜멘 쇼핑 센터 ""굿윈""",50,튜멘,중부
51,"튜멘 쇼핑 센터 ""그린 비치""",51,튜멘,중부
52,"우파 TC ""중부""",52,우파,서부
53,"우파 TC ""가족""2",53,우파,서부
54,"Khimki ТЦ ""메가""",54,힘키,서부
55,디지털 창고 1C-Online,55,기타,기타
56,"체 호프 SEC ""카니발""",56,기타,기타
57,"Yakutsk Ordzhonikidze, 56",57,야쿠츠크,동부
58,야쿠 츠크 센트럴 쇼핑 센터,58,야쿠츠크,동부
59,"야로 슬라 블 쇼핑 센터 ""Altair""",59,야로슬라블,서부

In [11]:
df_train

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
0,02.01.2013,0,59,22154,999.00,1.0
1,03.01.2013,0,25,2552,899.00,1.0
2,05.01.2013,0,25,2552,899.00,-1.0
3,06.01.2013,0,25,2554,1709.05,1.0
4,15.01.2013,0,25,2555,1099.00,1.0
5,10.01.2013,0,25,2564,349.00,1.0
6,02.01.2013,0,25,2565,549.00,1.0
7,04.01.2013,0,25,2572,239.00,1.0
8,11.01.2013,0,25,2572,299.00,1.0
9,03.01.2013,0,25,2573,299.00,3.0
10,03.01.2013,0,25,2574,399.00,2.0
11,05.01.2013,0,25,2574,399.00,1.0
12,07.01.2013,0,25,2574,399.00,1.0
13,08.01.2013,0,25,2574,399.00,2.0
14,10.01.2013,0,25,2574,399.00,1.0
15,11.01.2013,0,25,2574,399.00,2.0
16,13.01.2013,0,25,2574,399.00,1.0
17,16.01.2013,0,25,2574,399.00,1.0
18,26.01.2013,0,25,2574,399.00,1.0
19,27.01.2013,0,25,2574,399.00,1.0
20,09.01.2013,0,25,2593,279.00,1.0
21,16.01.2013,0,25,2604,299.00,1.0
22,27.01.2013,0,25,2604,299.00,1.0
23,27.01.2013,0,25,2607,279.00,1.0
24,29.01.2013,0,25,2607,279.00,1.0
25,27.01.2013,0,25,2609,1699.00,1.0
26,06.01.2013,0,25,2548,1708.95,1.0
27,26.01.2013,0,25,2611,299.00,1.0
28,02.01.2013,0,25,2546,299.00,1.0
29,06.01.2013,0,25,2515,1649.00,1.0
...,...,...,...,...,...,...
2935819,16.10.2015,33,25,7789,1799.00,1.0
2935820,22.10.2015,33,25,7790,799.00,1.0
2935821,22.10.2015,33,25,7791,899.50,1.0
2935822,17.10.2015,33,25,7632,2310.00,1.0
2935823,26.10.2015,33,25,7487,299.00,1.0
2935824,14.10.2015,33,25,7029,999.00,1.0
2935825,23.10.2015,33,25,7460,299.00,1.0
2935826,04.10.2015,33,25,7233,599.00,1.0
2935827,18.10.2015,33,25,7308,349.00,1.0
2935828,21.10.2015,33,25,7233,479.00,1.0
2935829,03.10.2015,33,25,7233,599.00,1.0
2935830,11.10.2015,33,25,7286,299.00,1.0
2935831,22.10.2015,33,25,7187,299.00,1.0
2935832,26.10.2015,33,25,7484,299.00,1.0
2935833,22.10.2015,33,25,7308,349.00,1.0
2935834,29.10.2015,33,25,7235,298.00,1.0
2935835,18.10.2015,33,25,7327,349.00,1.0
2935836,22.10.2015,33,25,7327,349.00,1.0
2935837,24.10.2015,33,25,7328,249.00,1.0
2935838,17.10.2015,33,25,7338,349.00,1.0
2935839,24.10.2015,33,25,7315,399.00,1.0
2935840,31.10.2015,33,25,7409,299.00,1.0
2935841,11.10.2015,33,25,7393,349.00,1.0
2935842,10.10.2015,33,25,7384,749.00,1.0
2935843,09.10.2015,33,25,7409,299.00,1.0
2935844,10.10.2015,33,25,7409,299.00,1.0
2935845,09.10.2015,33,25,7460,299.00,1.0
2935846,14.10.2015,33,25,7459,349.00,1.0
2935847,22.10.2015,33,25,7440,299.00,1.0
2935848,03.10.2015,33,25,7460,299.00,1.0

In [14]:
df_newtrain = pd.merge(df_train,df_shops,on='shop_id')
df_newtrain

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,shop_name,location,direction
0,02.01.2013,0,59,22154,999.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
1,10.01.2013,0,59,22151,399.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
2,04.01.2013,0,59,5603,699.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
3,19.01.2013,0,59,5587,199.0,2.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
4,31.01.2013,0,59,5613,5571.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
5,10.01.2013,0,59,5623,699.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
6,14.01.2013,0,59,5623,699.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
7,10.01.2013,0,59,5629,2390.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
8,04.01.2013,0,59,5643,2390.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
9,17.01.2013,0,59,5643,2390.0,2.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
10,19.01.2013,0,59,5643,2390.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
11,02.01.2013,0,59,5994,298.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
12,13.01.2013,0,59,5992,499.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
13,17.01.2013,0,59,6000,299.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
14,17.01.2013,0,59,6009,1999.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
15,14.01.2013,0,59,6072,898.5,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
16,18.01.2013,0,59,6072,899.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
17,03.01.2013,0,59,6078,899.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
18,02.01.2013,0,59,6093,349.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
19,09.01.2013,0,59,6093,349.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
20,19.01.2013,0,59,6093,349.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
21,02.01.2013,0,59,6095,1699.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
22,06.01.2013,0,59,6122,2498.5,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
23,02.01.2013,0,59,6123,2499.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
24,20.01.2013,0,59,6131,549.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
25,02.01.2013,0,59,5592,3490.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
26,09.01.2013,0,59,6144,599.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
27,05.01.2013,0,59,5591,1890.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
28,14.01.2013,0,59,5575,1090.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
29,02.01.2013,0,59,5864,1799.0,1.0,"야로 슬라 블 쇼핑 센터 ""Altair""",야로슬라블,서부
...,...,...,...,...,...,...,...,...,...
2935819,20.10.2015,33,36,21671,399.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935820,26.10.2015,33,36,21676,149.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935821,29.10.2015,33,36,21759,249.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935822,28.10.2015,33,36,21811,199.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935823,18.10.2015,33,36,20611,2249.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935824,31.10.2015,33,36,14227,99.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935825,18.10.2015,33,36,20610,1099.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935826,27.10.2015,33,36,20405,2399.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935827,21.10.2015,33,36,17388,799.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935828,30.10.2015,33,36,17882,169.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935829,25.10.2015,33,36,17990,249.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935830,31.10.2015,33,36,18101,3799.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935831,27.10.2015,33,36,18146,298.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935832,24.10.2015,33,36,18280,199.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935833,24.10.2015,33,36,18378,199.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935834,18.10.2015,33,36,18417,229.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935835,27.10.2015,33,36,18464,229.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935836,22.10.2015,33,36,18497,229.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935837,27.10.2015,33,36,18499,229.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935838,22.10.2015,33,36,18825,399.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935839,24.10.2015,33,36,18910,399.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935840,25.10.2015,33,36,19650,299.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935841,31.10.2015,33,36,19985,199.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935842,31.10.2015,33,36,19817,449.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935843,30.10.2015,33,36,19894,199.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935844,30.10.2015,33,36,20231,169.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935845,18.10.2015,33,36,20334,1949.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935846,31.10.2015,33,36,20339,1549.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935847,31.10.2015,33,36,20352,1549.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부
2935848,18.10.2015,33,36,20602,1549.0,1.0,"노보시비르스크 TRC ""갤러리 노보 시비 르 스크""",노보시비르스크,중부

In [52]:
df_train= df_newtrain[["date","date_block_num","item_id","item_price","item_cnt_day","direction"]]
df_train

,date,date_block_num,item_id,item_price,item_cnt_day,direction
0,02.01.2013,0,22154,999.0,1.0,서부
1,10.01.2013,0,22151,399.0,1.0,서부
2,04.01.2013,0,5603,699.0,1.0,서부
3,19.01.2013,0,5587,199.0,2.0,서부
4,31.01.2013,0,5613,5571.0,1.0,서부
5,10.01.2013,0,5623,699.0,1.0,서부
6,14.01.2013,0,5623,699.0,1.0,서부
7,10.01.2013,0,5629,2390.0,1.0,서부
8,04.01.2013,0,5643,2390.0,1.0,서부
9,17.01.2013,0,5643,2390.0,2.0,서부
10,19.01.2013,0,5643,2390.0,1.0,서부
11,02.01.2013,0,5994,298.0,1.0,서부
12,13.01.2013,0,5992,499.0,1.0,서부
13,17.01.2013,0,6000,299.0,1.0,서부
14,17.01.2013,0,6009,1999.0,1.0,서부
15,14.01.2013,0,6072,898.5,1.0,서부
16,18.01.2013,0,6072,899.0,1.0,서부
17,03.01.2013,0,6078,899.0,1.0,서부
18,02.01.2013,0,6093,349.0,1.0,서부
19,09.01.2013,0,6093,349.0,1.0,서부
20,19.01.2013,0,6093,349.0,1.0,서부
21,02.01.2013,0,6095,1699.0,1.0,서부
22,06.01.2013,0,6122,2498.5,1.0,서부
23,02.01.2013,0,6123,2499.0,1.0,서부
24,20.01.2013,0,6131,549.0,1.0,서부
25,02.01.2013,0,5592,3490.0,1.0,서부
26,09.01.2013,0,6144,599.0,1.0,서부
27,05.01.2013,0,5591,1890.0,1.0,서부
28,14.01.2013,0,5575,1090.0,1.0,서부
29,02.01.2013,0,5864,1799.0,1.0,서부
...,...,...,...,...,...,...
2935819,20.10.2015,33,21671,399.0,1.0,중부
2935820,26.10.2015,33,21676,149.0,1.0,중부
2935821,29.10.2015,33,21759,249.0,1.0,중부
2935822,28.10.2015,33,21811,199.0,1.0,중부
2935823,18.10.2015,33,20611,2249.0,1.0,중부
2935824,31.10.2015,33,14227,99.0,1.0,중부
2935825,18.10.2015,33,20610,1099.0,1.0,중부
2935826,27.10.2015,33,20405,2399.0,1.0,중부
2935827,21.10.2015,33,17388,799.0,1.0,중부
2935828,30.10.2015,33,17882,169.0,1.0,중부
2935829,25.10.2015,33,17990,249.0,1.0,중부
2935830,31.10.2015,33,18101,3799.0,1.0,중부
2935831,27.10.2015,33,18146,298.0,1.0,중부
2935832,24.10.2015,33,18280,199.0,1.0,중부
2935833,24.10.2015,33,18378,199.0,1.0,중부
2935834,18.10.2015,33,18417,229.0,1.0,중부
2935835,27.10.2015,33,18464,229.0,1.0,중부
2935836,22.10.2015,33,18497,229.0,1.0,중부
2935837,27.10.2015,33,18499,229.0,1.0,중부
2935838,22.10.2015,33,18825,399.0,1.0,중부
2935839,24.10.2015,33,18910,399.0,1.0,중부
2935840,25.10.2015,33,19650,299.0,1.0,중부
2935841,31.10.2015,33,19985,199.0,1.0,중부
2935842,31.10.2015,33,19817,449.0,1.0,중부
2935843,30.10.2015,33,19894,199.0,1.0,중부
2935844,30.10.2015,33,20231,169.0,1.0,중부
2935845,18.10.2015,33,20334,1949.0,1.0,중부
2935846,31.10.2015,33,20339,1549.0,1.0,중부
2935847,31.10.2015,33,20352,1549.0,1.0,중부
2935848,18.10.2015,33,20602,1549.0,1.0,중부

In [54]:
df_train.rename(columns={'direction': 'shop_id'}, inplace=True)
df_train.is_copy = False
df_train

               date  date_block_num  item_id  item_price  item_cnt_day shop_id
0        02.01.2013               0    22154       999.0           1.0      서부
1        10.01.2013               0    22151       399.0           1.0      서부
2        04.01.2013               0     5603       699.0           1.0      서부
3        19.01.2013               0     5587       199.0           2.0      서부
4        31.01.2013               0     5613      5571.0           1.0      서부
5        10.01.2013               0     5623       699.0           1.0      서부
6        14.01.2013               0     5623       699.0           1.0      서부
7        10.01.2013               0     5629      2390.0           1.0      서부
8        04.01.2013               0     5643      2390.0           1.0      서부
9        17.01.2013               0     5643      2390.0           2.0      서부
10       19.01.2013               0     5643      2390.0           1.0      서부
11       02.01.2013               0     5994       298.0           1.0      서부
12       13.01.2013               0     5992       499.0           1.0      서부
13       17.01.2013               0     6000       299.0           1.0      서부
14       17.01.2013               0     6009      1999.0           1.0      서부
15       14.01.2013               0     6072       898.5           1.0      서부
16       18.01.2013               0     6072       899.0           1.0      서부
17       03.01.2013               0     6078       899.0           1.0      서부
18       02.01.2013               0     6093       349.0           1.0      서부
19       09.01.2013               0     6093       349.0           1.0      서부
20       19.01.2013               0     6093       349.0           1.0      서부
21       02.01.2013               0     6095      1699.0           1.0      서부
22       06.01.2013               0     6122      2498.5           1.0      서부
23       02.01.2013               0     6123      2499.0           1.0      서부
24       20.01.2013               0     6131       549.0           1.0      서부
25       02.01.2013               0     5592      3490.0           1.0      서부
26       09.01.2013               0     6144       599.0           1.0      서부
27       05.01.2013               0     5591      1890.0           1.0      서부
28       14.01.2013               0     5575      1090.0           1.0      서부
29       02.01.2013               0     5864      1799.0           1.0      서부
...             ...             ...      ...         ...           ...     ...
2935819  20.10.2015              33    21671       399.0           1.0      중부
2935820  26.10.2015              33    21676       149.0           1.0      중부
2935821  29.10.2015              33    21759       249.0           1.0      중부
2935822  28.10.2015              33    21811       199.0           1.0      중부
2935823  18.10.2015              33    20611      2249.0           1.0      중부
2935824  31.10.2015              33    14227        99.0           1.0      중부
2935825  18.10.2015              33    20610      1099.0           1.0      중부
2935826  27.10.2015              33    20405      2399.0           1.0      중부
2935827  21.10.2015              33    17388       799.0           1.0      중부
2935828  30.10.2015              33    17882       169.0           1.0      중부
2935829  25.10.2015              33    17990       249.0           1.0      중부
2935830  31.10.2015              33    18101      3799.0           1.0      중부
2935831  27.10.2015              33    18146       298.0           1.0      중부
2935832  24.10.2015              33    18280       199.0           1.0      중부
2935833  24.10.2015              33    18378       199.0           1.0      중부
2935834  18.10.2015              33    18417       229.0           1.0      중부
2935835  27.10.2015              33    18464       229.0           1.0      중부
2935836  22.10.2015              33    18497       229.0           1.0      중부
2935837  27.10.2015              33    18499       229.0           1.0      중부
2935838  22.10.2015              33    18825       399.0           1.0      중부
2935839  24.10.2015              33    18910       399.0           1.0      중부
2935840  25.10.2015              33    19650       299.0           1.0      중부
2935841  31.10.2015              33    19985       199.0           1.0      중부
2935842  31.10.2015              33    19817       449.0           1.0      중부
2935843  30.10.2015              33    19894       199.0           1.0      중부
2935844  30.10.2015              33    20231       169.0           1.0      중부
2935845  18.10.2015              33    20334      1949.0           1.0      중부
2935846  31.10.2015              33    20339      1549.0           1.0      중부
2935847  31.10.2015              33    20352      1549.0           1.0      중부
2935848  18.10.2015              33    20602      1549.0           1.0      중부

[2935849 rows x 6 columns]

In [29]:
df_test

            ID  shop_id  item_id
0            0        5     5037
1            1        5     5320
2            2        5     5233
3            3        5     5232
4            4        5     5268
5            5        5     5039
6            6        5     5041
7            7        5     5046
8            8        5     5319
9            9        5     5003
10          10        5     4806
11          11        5     4843
12          12        5     4607
13          13        5     4869
14          14        5     4870
15          15        5     4872
16          16        5     4874
17          17        5     4678
18          18        5     4892
19          19        5     4964
20          20        5     4717
21          21        5     5002
22          22        5     5823
23          23        5     5814
24          24        5     5900
25          25        5     5907
26          26        5     5908
27          27        5     5643
28          28        5     5657
29          29        5     5675
...        ...      ...      ...
214170  214170       45    14543
214171  214171       45    19253
214172  214172       45    17957
214173  214173       45    12470
214174  214174       45     7543
214175  214175       45     6661
214176  214176       45    11137
214177  214177       45    11489
214178  214178       45     9782
214179  214179       45     2972
214180  214180       45    19889
214181  214181       45    20650
214182  214182       45     5665
214183  214183       45     9978
214184  214184       45    10767
214185  214185       45    14443
214186  214186       45    14341
214187  214187       45     5401
214188  214188       45     9500
214189  214189       45    16007
214190  214190       45     3280
214191  214191       45     4393
214192  214192       45     4352
214193  214193       45    18049
214194  214194       45    18027
214195  214195       45    18454
214196  214196       45    16188
214197  214197       45    15757
214198  214198       45    19648
214199  214199       45      969

[214200 rows x 3 columns]

In [32]:
df_newtest= pd.merge(df_test,df_shops,on='shop_id')
df_newtest.head(5)

   ID  shop_id  item_id                      shop_name location direction
0   0        5     5037  볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"     볼로그다        서부
1   1        5     5320  볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"     볼로그다        서부
2   2        5     5233  볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"     볼로그다        서부
3   3        5     5232  볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"     볼로그다        서부
4   4        5     5268  볼 로그 다 쇼핑 및 엔터테인먼트 센터 "마멀레이드"     볼로그다        서부

In [55]:
df_test=df_newtest[["ID","item_id","direction"]]
df_test

            ID  item_id direction
0            0     5037        서부
1            1     5320        서부
2            2     5233        서부
3            3     5232        서부
4            4     5268        서부
5            5     5039        서부
6            6     5041        서부
7            7     5046        서부
8            8     5319        서부
9            9     5003        서부
10          10     4806        서부
11          11     4843        서부
12          12     4607        서부
13          13     4869        서부
14          14     4870        서부
15          15     4872        서부
16          16     4874        서부
17          17     4678        서부
18          18     4892        서부
19          19     4964        서부
20          20     4717        서부
21          21     5002        서부
22          22     5823        서부
23          23     5814        서부
24          24     5900        서부
25          25     5907        서부
26          26     5908        서부
27          27     5643        서부
28          28     5657        서부
29          29     5675        서부
...        ...      ...       ...
214170  214170    14543        서부
214171  214171    19253        서부
214172  214172    17957        서부
214173  214173    12470        서부
214174  214174     7543        서부
214175  214175     6661        서부
214176  214176    11137        서부
214177  214177    11489        서부
214178  214178     9782        서부
214179  214179     2972        서부
214180  214180    19889        서부
214181  214181    20650        서부
214182  214182     5665        서부
214183  214183     9978        서부
214184  214184    10767        서부
214185  214185    14443        서부
214186  214186    14341        서부
214187  214187     5401        서부
214188  214188     9500        서부
214189  214189    16007        서부
214190  214190     3280        서부
214191  214191     4393        서부
214192  214192     4352        서부
214193  214193    18049        서부
214194  214194    18027        서부
214195  214195    18454        서부
214196  214196    16188        서부
214197  214197    15757        서부
214198  214198    19648        서부
214199  214199      969        서부

[214200 rows x 3 columns]

In [58]:
df_test.rename(columns={'direction': 'shop_id'}, inplace=True)
df_test.is_copy = False
df_test

            ID  item_id shop_id
0            0     5037      서부
1            1     5320      서부
2            2     5233      서부
3            3     5232      서부
4            4     5268      서부
5            5     5039      서부
6            6     5041      서부
7            7     5046      서부
8            8     5319      서부
9            9     5003      서부
10          10     4806      서부
11          11     4843      서부
12          12     4607      서부
13          13     4869      서부
14          14     4870      서부
15          15     4872      서부
16          16     4874      서부
17          17     4678      서부
18          18     4892      서부
19          19     4964      서부
20          20     4717      서부
21          21     5002      서부
22          22     5823      서부
23          23     5814      서부
24          24     5900      서부
25          25     5907      서부
26          26     5908      서부
27          27     5643      서부
28          28     5657      서부
29          29     5675      서부
...        ...      ...     ...
214170  214170    14543      서부
214171  214171    19253      서부
214172  214172    17957      서부
214173  214173    12470      서부
214174  214174     7543      서부
214175  214175     6661      서부
214176  214176    11137      서부
214177  214177    11489      서부
214178  214178     9782      서부
214179  214179     2972      서부
214180  214180    19889      서부
214181  214181    20650      서부
214182  214182     5665      서부
214183  214183     9978      서부
214184  214184    10767      서부
214185  214185    14443      서부
214186  214186    14341      서부
214187  214187     5401      서부
214188  214188     9500      서부
214189  214189    16007      서부
214190  214190     3280      서부
214191  214191     4393      서부
214192  214192     4352      서부
214193  214193    18049      서부
214194  214194    18027      서부
214195  214195    18454      서부
214196  214196    16188      서부
214197  214197    15757      서부
214198  214198    19648      서부
214199  214199      969      서부

[214200 rows x 3 columns]